#!/usr/bin/env python3
"""Generate src/aiotask/_awaitify.pyi with typed overloads for node."""

from pathlib import Path

MAX_PARAMS = 10
OUTPUT = Path(__file__).parent.parent / "src" / "aiotask" / "_awaitify.pyi"


def make_type_vars(n: int) -> str:
    return ", ".join(f"T{i}" for i in range(1, n + 1))


def make_param_list(n: int) -> str:
    return ", ".join(f"T{i}" for i in range(1, n + 1))


def make_awaitable_param_list(n: int) -> str:
    return ", ".join(f"T{i} | Awaitable[T{i}]" for i in range(1, n + 1))


def make_return_type(awaitable_params: str) -> str:
    inline = f") -> Callable[[{awaitable_params}], Coroutine[Any, Any, R]]: ..."
    if len(inline) <= 120:
        return inline
    param_lines = "\n".join(f"        {p}," for p in awaitable_params.split(", "))
    return (
        ") -> Callable[\n"
        "    [\n"
        f"{param_lines}\n"
        "    ],\n"
        "    Coroutine[Any, Any, R],\n"
        "]: ..."
    )


EXTRA_PARAMS = (
    "    /,\n    deps: Sequence[Awaitable[Any]] = ...,\n"
    "    track: bool = ...,\n    auto_progress: bool = ...,\n"
)


def generate() -> str:
    lines: list[str] = []
    lines.append("# Auto-generated by scripts/generate_stubs.py — do not edit manually.")
    lines.append("from collections.abc import Awaitable, Callable, Coroutine, Sequence")
    lines.append("from typing import Any, overload")
    lines.append("")

    # Zero-arg overloads
    lines.append("# --- 0 parameters ---")
    lines.append("@overload")
    lines.append("def node[R](")
    lines.append("    func: Callable[[], Coroutine[Any, Any, R]],")
    lines.append(EXTRA_PARAMS + ") -> Callable[[], Coroutine[Any, Any, R]]: ...")
    lines.append("")
    lines.append("@overload")
    lines.append("def node[R](")
    lines.append("    func: Callable[[], R],")
    lines.append(EXTRA_PARAMS + ") -> Callable[[], Coroutine[Any, Any, R]]: ...")
    lines.append("")

    for n in range(1, MAX_PARAMS + 1):
        type_vars = make_type_vars(n)
        params = make_param_list(n)
        awaitable_params = make_awaitable_param_list(n)
        lines.append(f"# --- {n} parameter{'s' if n != 1 else ''} ---")
        # async-original overload (more specific, comes first)
        lines.append("@overload")
        lines.append(f"def node[{type_vars}, R](")
        lines.append(f"    func: Callable[[{params}], Coroutine[Any, Any, R]],")
        lines.append(EXTRA_PARAMS + make_return_type(awaitable_params))
        lines.append("")
        # sync-original overload
        lines.append("@overload")
        lines.append(f"def node[{type_vars}, R](")
        lines.append(f"    func: Callable[[{params}], R],")
        lines.append(EXTRA_PARAMS + make_return_type(awaitable_params))
        lines.append("")

    # catch-all fallback
    lines.append("# --- fallback ---")
    lines.append("@overload")
    lines.append("def node(")
    lines.append("    func: Callable[..., Any],")
    lines.append(EXTRA_PARAMS + ") -> Callable[..., Coroutine[Any, Any, Any]]: ...")
    lines.append("")
    lines.append(
        "def node(\n"
        "    func: Any,\n"
        f"{EXTRA_PARAMS}"
        ") -> Any: ..."
    )

    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    content = generate()
    OUTPUT.write_text(content)
    print(f"Written {OUTPUT}")
